site_name: OPENSEIZE

# custom color scheme
extra_css:
    - stylesheets/extra_styles.css

# declare plugins
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    members_order: source
    - mkdocs-jupyter

# declare extensions
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

# use standard material theme
theme:
    name: material

    # two toggleable color palettes
    palette:
        - scheme: space
          toggle:
            icon: material/brightness-7
            name: Dark Mode

        - scheme: slate
          primary: black
          toggle:
              icon: material/brightness-4
              name: Light Mode

    # logos at site name & window tab
    logo: 'imgs/tinylogo.png'
    favicon: 'imgs/tinylogo.png'

    features:
        # add tabs to header & keep visible on scroll
        - navigation.tabs
        - navigation.tabs.sticky

    # add icon to header for github repo link
    icon:
        repo: fontawesome/brands/github

# link to github repository
repo_url: https://github.com/mscaudill/openseize
repo_name: mscaudill/openseize

# make pages non-editable
edit_uri: ""

# configure navigation pane
nav:
    - Home: index.md
    - Quickstart: quickstart.ipynb
    - Tutorials:
        - 'Producers': 'tutorials/producers.ipynb'
        - 'File Reading':
          - 'EDF Format': 'tutorials/edf_format.ipynb'
          - 'Other Formats': 'tutorials/other_formats.ipynb'
        - 'Filtering': 'tutorials/filtering.ipynb'
        - 'Resampling': 'tutorials/resampling.ipynb'
        - 'Fourier Transform': 'tutorials/fourier_transform.ipynb'
        - 'Spectral Analysis': 'tutorials/spectra.ipynb'
    - Reference:
        - Producers:
          - producer: 'producer/producer.md'
        - 'File IO':
          - 'Dialogs': 'file_io/dialogs.md'
          - EDF:
            - Introduction: 'file_io/edf/edf_intro.md'
            - Reader: 'file_io/edf/edf_reader.md'
            - Writer: 'file_io/edf/edf_writer.md'
            - Splitter: 'file_io/edf/edf_splitter.md'
          - Annotations:
            - Introduction: 'file_io/annotations/ann_intro.md'
            - Pinnacle: 'file_io/annotations/pinnacle.md'
            - as_mask: 'file_io/annotations/as_mask.md'
        - Filters:
            - 'FIR Filters':
              - Introduction: 'filtering/firs/fir_intro.md'
              - Kaiser: 'filtering/firs/kaiser.md'
              - Rectangular: 'filtering/firs/rectangular.md'
              - Bartlett: 'filtering/firs/bartlett.md'
              - Hann: 'filtering/firs/hann.md'
              - Hamming: 'filtering/firs/hamming.md'
              - Blackman: 'filtering/firs/blackman.md'
              - Remez: 'filtering/firs/remez.md'
            - 'IIR Filters':
              - Introduction: 'filtering/iirs/iir_intro.md'
              - Butterworth: 'filtering/iirs/butter.md'
              - 'Chebyshev I': 'filtering/iirs/cheby1.md'
              - 'Chebyshev II': 'filtering/iirs/cheby2.md'
              - Elliptical: 'filtering/iirs/ellip.md'
              - Notch: 'filtering/iirs/notch.md'
            - 'Special':
              - Hilbert: 'filtering/special/hilbert.md'
        - Resampling:
            - Resampling: 'resampling/resampling.md'
        - Spectra:
            - Estimators:
              - Power Spectrum: 'spectra/estimators/psd.md'
              - Short-time Fourier Transform: 'spectra/estimators/stft.md'
            - Metrics: 'spectra/spectra_metrics.md'
            - Plotting: 'spectra/spectra_plotting.md'

    - About: about.md

# reflect changes immediately during dev.
watch:
    - src/openseize/

# Footer icon components
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mscaudill


