name: ❓ Question
description: Ask a question
labels: [question]
title: "[Quest]: <Title>"
body:

  # validate if this issue already exist
  - type: checkboxes
    attributes:
      label: Has this question been asked before?
      options:
      - label: I have searched the existing issues for this question.
        required: true

  # question box
  - type: textarea
    attributes:
      label: Question
      description: >
        Tip:  You can attach images or log files by clicking 
        this area to highlight it and then dragging files in.
    validations:
      required: true

  # Code of Conduct
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: > 
        By submitting this issue, you agree to follow our 
        [Code of Conduct](
        https://github.com/mscaudill/openseize/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
